apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mywebb-app
  labels:
    app:  web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  template:
    metadata:
      labels:
        app:  web
    spec:
      containers:
      - name:  my-app
        image:  docker.io/cloudnat/photo-img
        ports:
        - containerPort:  80
          name: my-app
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
   